In [2]:
from pathlib import Path
import pandas as pd

DF_PATH = Path("D:\\Frans\\Github Repo\\Analysis-of-Air-Quality-Dataset\\Data\\raw")

sample = pd.read_csv(DF_PATH / "PRSA_Data_Aotizhongxin_20130301-20170228.csv")

sample.info()
sample.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34139 non-null  float64
 6   PM10     34346 non-null  float64
 7   SO2      34129 non-null  float64
 8   NO2      34041 non-null  float64
 9   CO       33288 non-null  float64
 10  O3       33345 non-null  float64
 11  TEMP     35044 non-null  float64
 12  PRES     35044 non-null  float64
 13  DEWP     35044 non-null  float64
 14  RAIN     35044 non-null  float64
 15  wd       34983 non-null  object
 16  WSPM     35050 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,4.0,7.0,300.0,77.0,-0.7,1023.0,-18.8,0.0,NNW,4.4,Aotizhongxin
1,2,2013,3,1,1,8.0,8.0,4.0,7.0,300.0,77.0,-1.1,1023.2,-18.2,0.0,N,4.7,Aotizhongxin
2,3,2013,3,1,2,7.0,7.0,5.0,10.0,300.0,73.0,-1.1,1023.5,-18.2,0.0,NNW,5.6,Aotizhongxin
3,4,2013,3,1,3,6.0,6.0,11.0,11.0,300.0,72.0,-1.4,1024.5,-19.4,0.0,NW,3.1,Aotizhongxin
4,5,2013,3,1,4,3.0,3.0,12.0,12.0,300.0,72.0,-2.0,1025.2,-19.5,0.0,N,2.0,Aotizhongxin

In [3]:
sample.isnull().sum()

No            0
year          0
month         0
day           0
hour          0
PM2.5       925
PM10        718
SO2         935
NO2        1023
CO         1776
O3         1719
TEMP         20
PRES         20
DEWP         20
RAIN         20
wd           81
WSPM         14
station       0
dtype: int64

In [6]:
sample.duplicated().sum()

np.int64(0)

In [11]:
polutan = sample[["PM2.5", "PM10", "SO2", "NO2", "CO", "O3"]]
polutan.describe()

,PM2.5,PM10,SO2,NO2,CO,O3
count,34139.000000,34346.000000,34129.000000,34041.000000,33288.000000,33345.000000
mean,82.773611,110.060391,17.375901,59.305833,1262.945145,56.353358
std,82.135694,95.223005,22.823017,37.116200,1221.436236,57.916327
min,3.000000,2.000000,0.285600,2.000000,100.000000,0.214200
25%,22.000000,38.000000,3.000000,30.000000,500.000000,8.000000
50%,58.000000,87.000000,9.000000,53.000000,900.000000,42.000000
75%,114.000000,155.000000,21.000000,82.000000,1500.000000,82.000000
max,898.000000,984.000000,341.000000,290.000000,10000.000000,423.000000

In [12]:
weather = sample[["TEMP", "PRES", "DEWP", "RAIN", "wd", "WSPM"]]
weather.describe()

               TEMP          PRES          DEWP          RAIN          WSPM
count  35044.000000  35044.000000  35044.000000  35044.000000  35050.000000
mean      13.584607   1011.846920      3.123062      0.067421      1.708496
std       11.399097     10.404047     13.688896      0.910056      1.204071
min      -16.800000    985.900000    -35.300000      0.000000      0.000000
25%        3.100000   1003.300000     -8.100000      0.000000      0.900000
50%       14.500000   1011.400000      3.800000      0.000000      1.400000
75%       23.300000   1020.100000     15.600000      0.000000      2.200000
max       40.500000   1042.000000     28.500000     72.500000     11.200000